services:
  vote-app:
    image: kerdainodev/vote-app:latest
    ports:
      - "5050:5000"
    env_file:
      - .env
    depends_on:
      - db

  result-app:
    image: kerdainodev/result-app:latest
    ports:
      - "5001:5001"
    env_file:
      - .env
    depends_on:
      - db

  worker:
    image: kerdainodev/worker:latest
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: voting_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data: